### ISSUE TITLE
document context manager

### ISSUE THREAD

**Issue by whit537** [gratipay/filesystem_tree.py#10]
I merged #8 without demanding a doc update. My bad.

**Comment by whit537** [comment]
Let's knock this out and then make a release so we can see how #15 behaves on PyPI. :)

**Comment by pjz** [comment]
I'm unclear what needs documentation.  It's now a context manager, which has a specific python meaning.

**Comment by pjz** [comment]
There's docs there already that indicate that it is now one.

**Comment by whit537** [comment]
> There's docs there already that indicate that it is now one.

Really? I missed that. You mean in the `__enter__` and `__exit__` docstrings? Those don't hit the [published docs](http://filesystem-tree-py.readthedocs.org/en/latest/).

Anyway, I'm on it. PR forthcoming ...

**Comment by pjz** [comment]
That's what I meant - I didn't realize they didn't get picked up; I don't know sphinx that well.

**Comment by whit537** [comment]
Ah, gotcha.
